"""add ethnicity to user

Revision ID: 67175908a5e7
Revises: 76434bd2d8ea
Create Date: 2026-03-14 19:43:33.781207

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '67175908a5e7'
down_revision = '76434bd2d8ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ethnicity', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ethnicity')
    # ### end Alembic commands ###
